version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          environment:
            CYPRESS_RECORD_KEY: 91a087ce-f5d1-43ca-98b8-0dfc30b88300
          start: npm start
          requires:
            - cypress/install 
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines
